# Generated by Django 5.1.6 on 2025-02-11 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.TextField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('en cours', 'En cours'), ('livrée', 'Livrée'), ('annulée', 'Annulée')], default='en attente', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
